package helpers

func Init() []Biodata {
	biodata := []Biodata{
		{},
		{
			Nama:      "Aldi Resaldi Maulana",
			Alamat:    "Indonesia",
			Pekerjaan: "Software Engineer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Vera Leananda",
			Alamat:    "Indonesia",
			Pekerjaan: "UX Designer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Afina Putri Dayanti",
			Alamat:    "Semarang",
			Pekerjaan: "Quality Assurance Engineer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Eric Anthony",
			Alamat:    "Indonesia",
			Pekerjaan: "Software Engineer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Nicholas Saputra",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Dameethia Angeline",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Thomas Stephen ",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Erico Jochsen",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Clara Tanudy",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Mario",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Kelvin",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Michelle Augustine",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Indri Yani Berutu",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Ronald Lie",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Dedi Chandra",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Jason Christian",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Jonathan Adelwin",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Marcel Hutama Jos",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Christopher Caleb",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Yosia Alvin Lie Fandy",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Andreas",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Dindha Ayu Aprilia",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Felix Ciawi",
			Alamat:    "Indonesia",
			Pekerjaan: "Quality Assurance Engineer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Kevin Jasson Lie",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Riva Audrey",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Gion Andrian",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Michael William Jonathan",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Wendy Bunandi",
			Alamat:    "Indonesia",
			Pekerjaan: "Quality Assurance Engineer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Renaldi Nurcahya Aditama",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Paulus Josianlie",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Teddy Adhitya",
			Alamat:    "Indonesia",
			Pekerjaan: "Quality Assurance Engineer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Naufal Ikhsan",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Kevin Joshwadi Malau",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Mursyied Qathafi",
			Alamat:    "Indonesia",
			Pekerjaan: "Quality Assurance Engineer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Josua Williams Hasiholan Tampubolon",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Joy Sepindo Lumbantobing",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Repi Maulana Risyan",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Falih Fauzan",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Haafidz Nurul Salim",
			Alamat:    "Indonesia",
			Pekerjaan: "Quality Assurance Engineer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Edy Pratamajaya",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Wildan Taufiq Abdul Aziz",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Ahmad Fadhil",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Randy Nasuta",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Pradika Fajar Rillo Pambudi",
			Alamat:    "Indonesia",
			Pekerjaan: "Quality Assurance Engineer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Muhammad Afif Ma'ruf",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Irham Sahbana",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Dwi Satria Patra",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Azka Nurhuda",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Irfan Arsyad",
			Alamat:    "Indonesia",
			Pekerjaan: "Quality Assurance Engineer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Toto Setiawan",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Ari Johand Lomo",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Laurensius Yuda Wicaksono Nugroho",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Regy Saputra",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Ryan Novary Pradana",
			Alamat:    "Indonesia",
			Pekerjaan: "Junior Back-End Developer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Ahmad Siddiq",
			Alamat:    "Indonesia",
			Pekerjaan: "Quality Assurance Engineer",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Ryan Nala Kusuma",
			Alamat:    "Indonesia",
			Pekerjaan: "Cloud Enginee",
			Alasan:    "Belajar Bahasa Go",
		},
		{
			Nama:      "Jaron Vincent Aulia",
			Alamat:    "Indonesia",
			Pekerjaan: "Cybersecurity ",
			Alasan:    "Belajar Bahasa Go",
		},
	}

	return biodata
}
